### ISSUE TITLE
Bug Encountered: viewDemographics ran twice.

### ISSUE THREAD

**Issue by eysszn** [Arvss07/9472-AppDev-Prelims-C#28]
I have encountered a bug where running the viewDemographics feature twice will automatically close the program. Please recheck.

**Comment by Arvss07** [comment]
I also encountered this bug a while ago, 
consider reviewing the `getCitizenAge` function maybe the bug is in there.

**Comment by Jeyah-05** [comment]
I'm having the same issue and it's occuring on my end as well. I attempted to search for the bug but it doesn't seem to be in the viewDemographics function.

**Comment by GiovanniL30** [comment]
Upon reviewing the issue, I found that the root cause of the bug occurs during the sorting by birthdate in the `compareCitizen` function. While the sorting works correctly on the first run, the program crashes on subsequent attempts because the data being passed becomes null. This happens because the `strcmp` function doesn't handle invalid or null data correctly when comparing the `birth_date`.

**Code conataining the bug:**

>    if (sort == birth_date)
    {
        return strcmp(citizen_a.birth_date, citizen_b.birth_date);
    }
    located on `citizen.c` file

**Issue Details:**
- When sorting by `birth_date, the `strcmp` function compares the birthdate strings directly.
- On subsequent runs, null or invalid data is passed, leading to a crash.

**Proposed Solution:**
I suggest creating a new function to calculate the age based on the `birth_date` and then compare the two ages for sorting. 

Thank You! :)
